### ISSUE TITLE
problems about loading word-embedding model

### ISSUE THREAD

**Issue by yayeoCddy** [woozzu/tagan#1]
I install fastText through your code, following:
git clone https://github.com/woozzu/fastText.py.git
cd fastText.py
python setup.py install

cd fasttext/cpp
make

and everything is ok. But there still are some errors like
Exception: fastText: Cannot load */fastText/wiki.en/wiki.en.bin due to C++ extension failed to allocate the memory

How can I solve it? Thank u~

**Comment by yayeoCddy** [comment]
I use the pyfasttext not fasttext to solve this problem
like:
from pyfasttext import FastText
word_embedding = FastText(args.fasttext_model)

**Comment by youngjung** [comment]
Installing latest fastText (https://github.com/facebookresearch/fastText/tree/master/python) fixed the problem for me.

Following fixes
- replace `fasttext` with `fastText` in `test.py`
- replace `word_embedding[w]` with `word_embedding.get_word_vector(w)` on [`line 74 in test.py`](https://github.com/woozzu/tagan/blob/7bc34c3991d0d8ae3f95d4161d9db35e40c6095b/test.py#L74)
