### ISSUE TITLE
hyperparameters in the pretrained model

### ISSUE THREAD

**Issue by davidpig** [woozzu/tagan#13]
Hi,
In the provided code there is a default setting of hyperparameters (e.g. default lambda_recon_loss is 0.2), is the pretrained model trained on that setting? If not, could you please provide the settings of hyperparameters to reproduce the pretrained model?

Thanks

**Comment by woozzu** [comment]
@davidpig Hi, the hyperparameters in our code are same as the experimental settings in our paper.

**Comment by davidpig** [comment]
Thank you very much for the prompt reply！ 😄
