### ISSUE TITLE
AttnGAN baseline model

### ISSUE THREAD

**Issue by varun19299** [woozzu/tagan#14]
The paper states in section 4 that a derivative of attention GAN was used as a baseline model (modified suitably by an image encoder).

Could you provide the model code used for the same?

**Comment by woozzu** [comment]
@varun19299 We basically adopted [the official AttnGAN code](https://github.com/taoxugit/AttnGAN) with an addition of an image encoder similar to that of our method.

**Comment by varun19299** [comment]
Were any hyperparameters modified for CelebA? ie... AttnGAN parameters.

> @woozzu <https://github.com/woozzu> We basically adopted the official AttnGAN code <https://github.com/taoxugit/AttnGAN> with an addition of an image encoder similar to that of our method.
> 

Thank you,
Varun

**Comment by woozzu** [comment]
@varun19299 We do not use CelebA dataset. We used the default hyperparameters for the part of the original network.

**Comment by varun19299** [comment]
Alright. Thank you!

Sorry. I meant CUB (birds) not celebA.
