### ISSUE TITLE
Is there any difference in results/training compared to training with joint loss?

### ISSUE THREAD

**Issue by k-eak** [woozzu/tagan#17]
Hi, 

Thank you for sharing your codes. I am wondering is there any difference in image quality/training when the networks are updated with joint loss term similarly to AttnGAN?

https://github.com/taoxugit/AttnGAN/blob/master/code/trainer.py#L271
https://github.com/taoxugit/AttnGAN/blob/master/code/trainer.py#L296

This would probably also improve the training time. Let me know if you tried training with joint loss.

Thank you.

**Comment by woozzu** [comment]
@k-eak Hi, I haven't tried the joint training. It could probably improve the current model.
