### ISSUE TITLE
Creation of custom captions

### ISSUE THREAD

**Issue by abhinav3** [woozzu/tagan#7]
Hi, Could you pls explain/share code that how could I create the captions encoding ".t7 files" for the custom captions I have for my images.

**Comment by woozzu** [comment]
@abhinav3 We are not responsible for creating *.t7 files. We only convert existing *.t7 files to our format. If you are going to prepare your own dataset for training, you don't need to create *.t7 files. I would suggest that you directly convert your dataset into our format. Please refer to [our code](https://github.com/woozzu/tagan/blob/master/data.py#L100-L116). In the code, `datum.char` is caption and `datum.img` is path of image file. For more details of the variables, please also refer to one of *.t7 files.

**Comment by abhinav3** [comment]
Thanks @woozzu for quick revert. I have gone through a sample "*.t7"  file.
The datum dictionary has four keys as show below : `{'char': tensor([[20, 20, 20,  ..., 20, 20, 20],
        [ 8,  8,  8,  ...,  8,  8,  8],
        [ 5,  9,  5,  ...,  9,  9,  9],
        ...,
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0]], dtype=torch.uint8), 'img': 'jpg/image_06734.jpg', 'txt': tensor([[ 0.0664, -0.0793,  0.0847,  ...,  0.0018,  0.1846,  0.0951],
        [ 0.0192, -0.0550, -0.1423,  ..., -0.0616,  0.0886,  0.0831],
        [ 0.0400, -0.0200,  0.1444,  ...,  0.0043,  0.1317, -0.0429],
        ...,
        [ 0.1213,  0.0238, -0.0126,  ..., -0.1251,  0.1515, -0.0064],
        [-0.0198, -0.0224, -0.0541,  ..., -0.1071,  0.0768,  0.0258],
        [ 0.0940, -0.0376, -0.0518,  ..., -0.1196,  0.0490,  0.0206]]), 'word': tensor([[ 292, 5383,  292,  292, 5383, 5383,  851, 5383, 5383, 5383],
        [  36, 2805, 1870, 4852, 2805, 2805, 2805, 2805, 2805, 2805],
        [4630,  732, 5253,   36, 2373, 2373, 1285, 2373, 2373, 2373],
        [ 292, 4608, 4630,  611, 5230,   36, 4740,  408, 5230, 4852],
        [2805, 2707,  292, 2466, 4608, 1121, 2707, 4608, 4720,   36],
        [4476,  381, 5363, 4630,   36, 4476, 2441,   36, 4608, 1034],
        [4608,  890, 4852,  381, 2707, 4608,   36, 1285,   36, 3820],
        [ 890, 2085,   36, 1285,  851, 2707, 1121,  851, 1285, 1034],
        [2085, 1285, 1938,  381,  381, 2373,  732,  999, 2589,  851],
        [2707,   36, 1035, 4450, 1608,  851, 1907, 5231, 1972,  381],
        [ 611, 1121,  292, 2707,  890,  999, 4852,    1, 2707, 3976],
        [ 851, 4476, 4164,  108,  292, 3976,    1,    1, 4852,    1],
        [ 999,  793, 3976,    1, 5231,    1,    1,    1, 5026,    1],
        [5231, 1444, 2707,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,  108,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1, 2707,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,  292,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1, 3748,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1, 5323,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1, 1608,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,  732,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1, 1598,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,    1,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,    1,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,    1,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,    1,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,    1,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,    1,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,    1,    1,    1,    1,    1,    1,    1,    1],
        [   1,    1,    1,    1,    1,    1,    1,    1,    1,    1]],
       dtype=torch.int16)}`

As you suggest that `datum.char` is caption and `datum.img` is path of image file, which are input to the TAGAN model.
Though I got confused with `datum.txt` and `datum.word`. If you are aware of usage for these keys, could you pls help us understand. Is it ok, if I don't take these two keys while training.
Thanks, Abhinav

**Comment by woozzu** [comment]
@abhinav3 Both `datum.txt` and `datum.word` are pre-computed embedding vectors used in the original paper where these *.t7 files come from. As far as I know, `txt` is character-based embedding vectors and `word` is word-based embedding vectors. In our paper, we do not use these vectors to deal with new sentences that are not included in the dataset.

**Comment by abhinav3** [comment]
Thanks a lot for the explanation!
