### ISSUE TITLE
Ask about computer environment

### ISSUE THREAD

**Issue by JunWangYi** [woozzu/tagan#9]
I have a problem when i run your demo,the shell showed that FileNotFoundError:[Error 2].So,I want to ask you about the computer environment.I use Linux system,python 3.5,cuda 9.0
I want to know your system,python version,cuda version,and the package(like pillow) version.
Thank you very much

**Comment by woozzu** [comment]
@JunWangYi Our code is not sensitive to system environment. Could you provide the entire error message with stack trace?

**Comment by JunWangYi** [comment]
![Screenshot from 2019-04-24 19-22-08](https://user-images.githubusercontent.com/48719780/56655868-84dacb80-66c6-11e9-85d9-59d48b297383.png)

**Comment by JunWangYi** [comment]
When i run the train_birds.sh,the problem above happened.

**Comment by woozzu** [comment]
@JunWangYi Can you check if the path really exists? After running ‘preprocess_caption.sh’, there must be a folder named ‘<datapath>_vec’.

**Comment by JunWangYi** [comment]
Thank you，this problem was solved,but I may ask you some more questions.Please forgive me for the inconvenience.

**Comment by woozzu** [comment]
@JunWangYi No problem. What’re your questions?

**Comment by JunWangYi** [comment]
![Screenshot from 2019-04-25 21-03-06](https://user-images.githubusercontent.com/48719780/56737723-9cd14e80-679d-11e9-8c01-34a9db364f43.png)

**Comment by JunWangYi** [comment]
How can I resolve this questions? thank you.

**Comment by woozzu** [comment]
@JunWangYi It's an out of memory error. Please reduce the batch size, which can be found in `train.py`.

**Comment by JunWangYi** [comment]
![Screenshot from 2019-04-29 11-43-54](https://user-images.githubusercontent.com/48719780/56875526-36d21900-6a74-11e9-9f19-6db37aedf1d6.png)
Do you know how can i resolve this question?Thank you.

**Comment by woozzu** [comment]
@JunWangYi It may be due to out of memory. I would suggest reducing batch size until you see some available memory space (e.g. hundreds of MBs).
